#include "exceptions.h"

const std::string HelpMessage::HELP_MESSAGE =
    "Command line arguments format:\n"
    "\t{program name} {path to input file} {path to output file}\n"
    "\t[-{filter name 1}[option 1][option 2]...]\n"
    "\t[-{filter name 2}[option 1][option 2]...]..\n"
    "\n"
    "\tWarning: Arguments starting with '-' are treated as filter names\n"
    "\n"
    "List of available filters:\n"
    "\t-crop width height\n"
    "\t\tCrop:\n"
    "\t\twidth, height - positive integers\n"
    "\t\tCrops the image to the given width and height, using the top left part of the image\n"
    "\t\tIf the requested width or height is larger than the source image, "
    "the accessible part of the image is displayed\n"
    "\t-gs\n"
    "\t\tGrayscale\n"
    "\t-neg\n"
    "\t\tNegative\n"
    "\t-sharp\n"
    "\t\tSharpening\n"
    "\t-edge threshold\n"
    "\t\tEdge detection:\n"
    "\t\tthreshold - floating point number in [0..1]\n"
    "\t\tThe best effect on raw photos is often achieved at threshold ~ 0.1\n"
    "\t-blur sigma\n"
    "\t\tGaussian blur:\n"
    "\t\tsigma - positive floating point number (blur radius in pixels)\n"
    "\t-hex a\n"
    "\t\tHexagonal pixellate:\n"
    "\t\ta - floating point number >= 2 (hexagon side length)\n"
    "\t\tMatches the image with colored regular hexagons\n"
    "\t-cryst n\n"
    "\t\tCrystallize:\n"
    "\t\tn - positive integer (approximate number of crystals)\n"
    "\t-vign alpha\n"
    "\t\tVignetting:\n"
    "\t\talpha - positive floating point number\n"
    "\t-bulge alpha\n"
    "\t\tBulge distorion:\n"
    "\t\talpha - positive floating point number in (0..1)\n"
    "\t-grid step width\n"
    "\t\tGrid:\n"
    "\t\tstep, width - positive integers\n"
    "\t\tOverlay a green grid\n";
